Repository dlr-gtlab/gtlab-core, pull requests merged in 2024-04, with the labels that each got.

#1159 implementation to add object to list of linkable objects
  src/core/process_management/gt_processcomponent.cpp
  src/core/process_management/gt_processcomponent.h
Labels: NeedsDiscussion

#1166 Resolve "Micro stutters when appending messages to the output dock"
  CHANGELOG.md
  src/app/dock_widgets/output/gt_outputdock.cpp
  src/app/dock_widgets/output/gt_outputdock.h
  src/app/dock_widgets/output/gt_styledlogmodel.cpp
Labels: category::gui, category::logging, type::bug

#1063 Resolve "Processes/Calculators-Area makes it difficult to add new taks"
  src/app/dock_widgets/process/gt_processdock.cpp
  src/app/dock_widgets/process/gt_processdock.h
Labels: category::processes, inprogress, type::bug
